name: "Test allpack"

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Test
              run: |
                  npm install
                  npm run test
            - name: Show files
              run: |
                  ls dist
            - name: Execute
              run: |
                  node dist/main.bundle.js
                  node dist/secondary.bundle.js
            - name: Cleanup
              run: |
                  rm -rf dist
                
